ini_open("saveData.ini");
global.key_up = ini_read_string("ControlsKeys", "up", 38);
global.key_right = ini_read_string("ControlsKeys", "right", 39);
global.key_left = ini_read_string("ControlsKeys", "left", 37);
global.key_down = ini_read_string("ControlsKeys", "down", 40);
global.key_jump = ini_read_string("ControlsKeys", "jump", 90);
global.key_slap = ini_read_string("ControlsKeys", "slap", 88);
global.key_attack = ini_read_string("ControlsKeys", "attack", 16);
global.key_start = 27;
ini_close();
global.key_upC = 32781;
global.key_rightC = 32784;
global.key_leftC = 32783;
global.key_downC = 32782;
global.key_jumpC = 32769;
global.key_slapC = 32771;
global.key_attackC = 32774;
global.key_startC = 32778;
key_up = keyboard_check(global.key_up) || gamepad_button_check(0, global.key_upC) || gamepad_axis_value(0, gp_axislv) < 0 || keyboard_check(vk_up);
key_up2 = keyboard_check_pressed(global.key_up) || gamepad_button_check_pressed(0, global.key_upC) || gamepad_axis_value(0, gp_axislv) < 0 || keyboard_check_pressed(vk_up);
key_right = keyboard_check(global.key_right) || gamepad_button_check(0, global.key_rightC) || gamepad_axis_value(0, gp_axislh) > 0 || keyboard_check(vk_right);
key_right2 = keyboard_check_pressed(global.key_right) || gamepad_button_check_pressed(0, global.key_rightC) || gamepad_axis_value(0, gp_axislh) > 0 || keyboard_check_pressed(vk_right);
key_left = -(keyboard_check(global.key_left) || gamepad_button_check(0, global.key_leftC) || gamepad_axis_value(0, gp_axislh) < 0 || keyboard_check(vk_left));
key_left2 = -(keyboard_check_pressed(global.key_left) || gamepad_button_check_pressed(0, global.key_leftC) || gamepad_axis_value(0, gp_axislh) < 0 || keyboard_check_pressed(vk_left));
key_down = keyboard_check(global.key_down) || gamepad_button_check(0, global.key_downC) || gamepad_axis_value(0, gp_axislv) > 0 || keyboard_check(vk_down);
key_down2 = keyboard_check_pressed(global.key_down) || gamepad_button_check_pressed(0, global.key_downC) || gamepad_axis_value(0, gp_axislv) > 0 || keyboard_check_pressed(vk_down);
key_jump = keyboard_check_pressed(global.key_jump) || gamepad_button_check_pressed(0, global.key_jumpC) || keyboard_check_pressed(ord("Z"));
key_jump2 = keyboard_check(global.key_jump) || gamepad_button_check(0, global.key_jumpC) || keyboard_check(ord("Z"));
key_slap = keyboard_check(global.key_slap) || gamepad_button_check(0, global.key_slapC) || keyboard_check(ord("X"));
key_slap2 = keyboard_check_pressed(global.key_slap) || gamepad_button_check_pressed(0, global.key_slapC) || keyboard_check_pressed(ord("X"));
key_attack = keyboard_check(global.key_attack) || gamepad_button_check(0, global.key_attackC) || gamepad_button_check(0, gp_face2) || gamepad_button_check(0, gp_shoulderl) || gamepad_button_check(0, gp_shoulderr) || gamepad_button_check(0, gp_shoulderl) || keyboard_check(vk_shift);
key_attack2 = keyboard_check_pressed(global.key_attack) || gamepad_button_check_pressed(0, global.key_attackC) || gamepad_button_check_pressed(0, gp_face2) || gamepad_button_check_pressed(0, gp_shoulderl) || gamepad_button_check_pressed(0, gp_shoulderr) || gamepad_button_check_pressed(0, gp_shoulderl) || keyboard_check_pressed(vk_shift);
key_start = keyboard_check_pressed(global.key_start) || gamepad_button_check_pressed(0, global.key_startC) || keyboard_check_pressed(vk_enter);
key_escape = keyboard_check_pressed(vk_escape) || gamepad_button_check(0, gp_select) || keyboard_check_pressed(vk_escape);
gamepad_set_axis_deadzone(0, 0.5);
